// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'channel': string;
  'chatItem': string;
  'chatList': string;
  'content': string;
  'footer': string;
  'header': string;
  'spin': string;
  'spinner': string;
  'spinnerWrapper': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
