// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dialog': string;
  'fade-in': string;
  'slide-in': string;
}
export const cssExports: CssExports;
export default cssExports;
