// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btnStart': string;
  'btnStop': string;
  'toolbar': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
