// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hovering': string;
  'inner': string;
  'outer': string;
  'pressing': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
