// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'balloon': string;
  'balloonWrapper': string;
  'list': string;
  'profile': string;
}
export const cssExports: CssExports;
export default cssExports;
