// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnHome': string;
  'leftPanel': string;
  'navBar': string;
  'rightPanel': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
