// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'channelBtn': string;
  'channelInfo': string;
  'displayName': string;
  'logoutBtn': string;
  'logoutBtnText': string;
  'profile': string;
  'profileWrapper': string;
  'userName': string;
  'wrapper': string;
  'wrapperOuter': string;
}
export const cssExports: CssExports;
export default cssExports;
