// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appDesc': string;
  'btnMine': string;
  'btnOther': string;
  'buttons': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
