// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnX': string;
  'label': string;
  'searchBar': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
