// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'heartbeat': string;
  'hoverInvert': string;
  'hoverNormal': string;
  'hoverPulse': string;
  'hoverZoom': string;
  'inner': string;
  'pulse': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
