// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'backdropBlur': string;
  'bgcolor-in': string;
  'blur-in': string;
  'dialog': string;
}
export const cssExports: CssExports;
export default cssExports;
