// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputText': string;
  'inputTextEdit': string;
  'inputTextView': string;
}
export const cssExports: CssExports;
export default cssExports;
