// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chatPanel': string;
  'gamePanel': string;
  'header': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
