// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btnText': string;
  'desc': string;
  'descText': string;
  'descTitle': string;
  'gameList': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
